-record(rms_node, {key :: rms_node:key(),
                   status = requested :: rms_node:status(),
                   cluster_key :: rms_cluster:key(),
                   node_name :: node(),
                   hostname = "" :: string(),
                   http_port :: pos_integer(),
                   pb_port :: pos_integer(),
                   disterl_port :: pos_integer(),
                   slave_id = "" :: string(),
                   container_path = "" :: string(),
                   persistence_id = "" :: string()}).
